# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/mayak/all/mayak.rbi
#
# mayak-0.0.1

module Mayak
end
module Mayak::Http
end

module Mayak::Monads
end
module Mayak::Monads::Maybe
  extend T::Generic
  extend T::Helpers
  extend T::Sig
end
module Mayak::Monads::Result
  extend T::Generic
  extend T::Helpers
  extend T::Sig
end
module Mayak::Monads::Try
  extend T::Generic
  extend T::Helpers
  extend T::Sig
end
