
name: CI

on:
  push:
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Gems cache
        uses: actions/cache@v4
        with:
          path: ~/gems
          key: gems-3.2-${{ hashFiles('*.gemspec', 'Gemfile') }}
          restore-keys: |
            gems-3.2-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path ~/gems
          bundle install --jobs 4 --retry 3
      - name: Runs Sorbet
        run: bundle exec srb tc
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.7.0"
          - "2.7"
          - "3.0.0"
          - "3.0"
          - "3.1.0"
          - "3.1"
          - "3.2.0"
          - "3.2"
          - "3.3.0"
          - "3.3"
          - "jruby-9.4"
        dependencies:
          - "edge"
          - "release"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Gems cache
        uses: actions/cache@v4
        with:
          path: ~/gems
          key: gems-${{ matrix.ruby }}-${{ hashFiles('*.gemspec', 'Gemfile') }}
          restore-keys: |
            gems-${{ matrix.ruby }}-
      - name: Install dependencies
        if: ${{ startsWith(matrix.ruby, '2.') }}
        run: |
          gem install bundler -v 2.4.22
          bundle config path ~/gems
          bundle install --jobs 4 --retry 3
      - name: Install dependencies
        if: ${{ ! startsWith(matrix.ruby, '2.') }}
        run: |
          gem install bundler
          bundle config path ~/gems
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rspec spec
